language: node_js
node_js:
  - "12"
addons:
  chrome: stable
before_script:
  - npm install -g @angular/cli@9.0.7
  - npm install
script:
  - npm run test-lib
after_success:
  - ./node_modules/.bin/codecov  -f test-output/mydaterangepicker/coverage-final.json
sudo: required
